// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfgzfkhbaftglpornohs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZ3pma2hiYWZ0Z2xwb3Jub2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTE5MjQsImV4cCI6MjA1OTg4NzkyNH0.2nFkHavWIqLWV5cGt9XzzB4IhFd_KE-NVwv7AExyFMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);